### PR TITLE
Implement Discord 'Slash commands'

### LINKED ISSUE #3: Use Discords 'Slash Commands'
[Improvement]

Maybe use Slash Commands instead of the `!` prefix.

More info: 

https://discord.com/developers/docs/interactions/slash-commands

https://github.com/serenity-rs/serenity/tree/current/examples/e14_slash_commands

### PR DESCRIPTION
**Pull request by Smephite**
Implement Discord slash commands to replace `!` prefixed bot commands. (Issue #3)

This will also be an quality of live improvement as e.g. all possible spell checks can be autocompleted.

### CODE REVIEW

**Comment by Triton171** [comment]
Do we know yet, how we can implement flags with slash commands?
If discord allows spaces in arguments, we could create commands like this: 
`/[COMMAND] [POSITIONAL_ARG1] [POSITIONAL_ARG2] <FLAGS>`

The only difficulty would be, how we deal with optional positional arguments: how can we distinguish an optional positional argument from the FLAGS argument?

**Comment by Smephite** [comment]
That was a fun merge....

**Comment by Smephite** [comment]
Functionality should be present, maybe some refactoring left.

**Comment by Triton171** [comment]
I've refactored it a bit, now it uses the app definition from `cli.rs` to automatically generate (and later parse) the slash commands. That should make life a bit easier and also ensure that behavior is consistent across commands.

There are a couple of things that we might wanna think about:
* Currently, flags are implemented as boolean options, but even though it's the intended way of implementing flags, it feels clunky always having to enter true/false additionally. A better way might be having them be String options and just leaving them blank.
The subcommand feature is also nice in some cases, but that would always require a strict hierarchy of options (and hide some flags from the user) which I don't like.
* For commands which start with a required field, you can still just type in the whole command without using the discord feature. That's nice, as it may be more convenient in some cases and isn't detrimental to anyone fully using slash commands.
We might wanna add a "dummy" field at the beginning of commands that don't have any required fields, making it a feature for all commands. For anyone not using it, nothing changes and they can still select the options in discords UI.

**Review by Triton171 — APPROVED** [review]

**Comment by Triton171** [comment]
Okay, I didn't really understand how exactly discord handles options in slash commands so my last 2 suggestions are probably not a good idea. As far as I can see, all commands work nicely now, except for:
* /upload doesn't work because discord doesn't allow attachments for slash commands. Other than requiring users to copy-paste the content of their character file into discord (which wouldn't make a lot of sense), I don't see how we can change anything about that
* /ini doesn't have nice autocompletion in discord, so entering a common command like "ini -all --rename" feels a bit annoying. My suggestion would be to implement the translation of subcommands from clap to discord (right now it only supports positional arguments, flags and flags that take a value). Then we could make "--all" and "--reset" subcommands (with the "all" subcommand allowing the "--rename" flag).

**Pull request merged**
