### PR TITLE
Fix #5 Only consider users in current channel

### LINKED ISSUE #5: Only consider users in current channel
When using `ini` do not load the characters from all users on the server but instead only those who are able to see the channel the command was typed in.

This will enable users to have different groups in different channels with different people without mixing them.

### PR DESCRIPTION
**Pull request by Smephite**
Bot will now search through all users currently online in the channel the command was typed to.

Also added some verbosity to console output on error (now includes the error type as well).

This PR fixes #5 

Had some minor problems while testing this as different servers had different behaviors? May need to check the required permissions.

### CODE REVIEW

**Comment by Triton171** [comment]
I've tested it and it seems like the function `fetch_discord_members` does not work correctly yet: In a channel with 3 members it only returned one ID (which did not belong to any of the members). I'm not sure what the reason for it is, or if it's reproducible but that definitely has to be fixed.

**Comment by Smephite** [comment]
Interestingly after a good night of sleep it does not work on either server anymore even though it worked on 1 out of 2 last night.

The bot only seems to see itself for some reason.

Also as test case I added
 ```rust
    match message.guild(&ctx.cache).await
    {
        Some(g) => match g.members(&ctx.http, Some(50), None).await {
            Ok(m) => println!("Succ {:?}", m),
            Err(e) => println!("members err => {:?}", e)
        },
        None => {
            println!("Guild => None");
        }
    }
``` 
and it will always exit with
```
members err => Http(UnsuccessfulRequest(ErrorResponse { status_code: 403, url: Url { scheme: "https", username: "", password: None, host: Some(Domain("discord.com")), port: None, path: "/api/v8/guilds/****/members", query: Some("&limit=50"), fragment: None }, error: "Missing Access" }))
```

So it seems like a some permission issue? The same applies with the version of a15d62c.

PS: The Bot has the permission `Administrator`

**Comment by Smephite** [comment]
Seems like we need to give the bot the permission `SERVER MEMBERS INTENT` in the dev portal.

TODO: Add to readme

**Comment by Smephite** [comment]
It seems like serenity caching is somewhat weird.  
The fix now reimplements the same things as the serenity API does but uses the objects returned from the message event as base. This fixes it?

**Comment by Smephite** [comment]
dc60279 also includes Readme changes concerning #2

**Pull request merged**
